blogs/urls.py
"""URL patterns for blogs app."""

from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Blogs list page.
    path('blogs/', views.blogs, name='blogs'),
    # Individual blog page.
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    # Page for adding a new blog topic.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for adding a new entry for a given blog
    path('new_entry/<int:blog_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry for a given blog
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

users/urls.py
"""Defines URL patterns for users app."""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    """A blog title model."""
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title

class Entry(models.Model):
    """A blog entry that users are going to write."""
    blog  = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            self.text = self.text[:50]
            return f"{self.text}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import Blog, Entry

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'public']
        labels = {'title': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db.models import Q
from .models import Blog, Entry
from .forms import BlogForm, EntryForm

def index(request):
    """Home page for our blogs app."""
    return render(request, 'blogs/index.html')

def check_blog_owner(blog, request):
    """Check the blog's owner."""
    if blog.owner != request.user:
        raise Http404

@login_required
def blogs(request):
    """Show blog list."""
    blogs = Blog.objects.filter(Q(owner=request.user) | Q(public=True)).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

@login_required
def blog(request, blog_id):
    """Show individual blog page."""
    blog = get_object_or_404(Blog, id=blog_id)
    entries = blog.entry_set.order_by('date_added')
    context = {'blog': blog, 'entries': entries}
    if blog.owner != request.user:
        if blog.public == True:
            return render(request, 'blogs/blog.html', context)
        else:
            raise Http404
    else:
        return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """Start a new blog."""
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:blogs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_entry(request, blog_id):
    """Add a new entry for a particular blog."""
    blog = get_object_or_404(Blog, id=blog_id)
    check_blog_owner(blog, request)

    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.blog = blog
            new_entry.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    blog = entry.blog
    check_blog_owner(blog, request)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id = blog.id)

    context = {'entry': entry, 'blog': blog, 'form':form}
    return render(request, 'blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>My blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            My blogs</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:blogs' %}">
                        Blogs</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text"}">Hello, {{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h3>{{ blog }}</h3>
{% endblock page_header %}

{% block content %}
    {% if blog.owner == request.user %}
        <p>
            <a href="{% url 'blogs:new_entry' blog.id %}">Add a new entry</a>
        </p>
    {% else %}
        <p>You aren't allowed to add entries for blogs you don't own.</p>
    {% endif %}

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'blogs:edit_entry' entry.id %}">
                    edit entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <li>There are no entries for this blog yet.</li>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h1>Blogs</h1>
{% endblock page_header %}

{% block content%}
    <ul>
        {% for blog in blogs %}
            <li><h3>
                <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a>
            </h3></li>
        {% empty %}
            <li>No blogs have been written yet.</li>
        {% endfor %}
    </ul>

    <h3><a href="{% url 'blogs:new_blog' %}">Add a new blog</a></h3>

{% endblock content %}

blogs/templates/blogs/edit_entry.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <p>
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a>
    </p>

    <p>Edit entry</p>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'blogs:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form%}
        {% buttons %}
            <button name="submit">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}
    

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">The most interesting blogs</h1>

        <p class="lead">Welcome to the My Blog. I hope it will become
            richer in content as the times goes by. You can add your own content
            and start a writing journey by making a user account. Good luck!</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Add a new blog</h3>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'blogs:new_blog' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form%}
        {% buttons %}
            <button name="submit">Add blog</button>
        {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blogs/new_entry.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <p>
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a>
    </p>
    <p>Add a new entry</p>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'blogs:new_entry' blog.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form%}
        {% buttons %}
            <button name="submit">Add new entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}